name = "bkuk"
account_id = "1fce1c702e3745b88a353360cfd485be"
compatibility_date = "2025-01-01"
kv_namespaces = [
  { binding = "LINKS", id = "1fce1c702e3745b88a353360cfd485be", preview_id = "1fce1c702e3745b88a353360cfd485be" }
]
